# Generated by Django 4.2.7 on 2023-11-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='otro_campo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
