# Generated by Django 4.2.7 on 2023-11-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_otro_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='otro_campo',
        ),
    ]
